server:
  port: 8123

spring:
  datasource:
    url: jdbc:mysql://101.132.112.59:3306/utf?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: "1823748191_Xry"

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 500MB

  redis:
    host: localhost
    port: 6379
    #url: redis://1357924680xry@101.132.112.59:6379
    timeout: 1000


mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: alex.UTFProject.entity

swagger:
  enable: true


jpa:
  properties:
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect

logback:
  dir: logs
  #文件名称
  filename:
    all: springboot-base-frame-all
    info: springboot-base-frame-info
    warn: springboot-base-frame-warn
    error: springboot-base-frame-error
  #文件的最大数量
  maxhistory: 10
  #文件的最大文件大小
  maxfilesize: 100MB
  #日志级别
  level: debug
  #日志字符编码
  charset: UTF-8
  #日志格式
  CONSOLE_LOG_PATTERN: '%d{yyyy-MM-dd HH:mm:ss.SSS} %boldYellow([%thread]) %highlight(%-5level) %boldGreen(%logger{50}) - %msg%n'
  FILE_LOG_PATTERN: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n'
